openapi: 3.0.3
info:
  title: Products API
  version: 1.0.0
  description: API to list products with filtering by category and sorting.
paths:
  /v1/products:
    get:
      summary: List products
      description: Retrieve a list of products, filterable by category and sortable by specific fields.
      operationId: getProducts
      tags:
        - Product
      parameters:
        - name: category
          in: query
          required: true
          description: Filter products by category
          schema:
            type: string
        - name: sort
          in: query
          required: true
          description: Sort products by one of the following fields
          schema:
            type: string
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Invalid query parameters
components:
  schemas:
    ProductResponse:
      type: object
      properties:
        sku:
          type: string
          example: 'SKU0001'
        price:
          type: number
          format: double
          example: 19.99
        description:
          type: string
          example: 'Wireless Mouse with ergonomic design'
        category:
          type: string
          example: 'Electronics'
      required:
        - sku
        - price
        - description
        - category
